server_url: https://192.168.1.215:6443
token: token             # Replace with a desired token
os:
  password: a     # Replace with a your password
install:
  mode: join
  mgmt_interface: eth0   # The management interface name
  device: /dev/sda       # The target disk to install
  iso_url: http://192.168.1.79/ipxe/harvester-amd64.iso
#  tty: ttyS1,115200n8   # For machines without a VGA console
